**Question 1 :** Use numpy to generate array of 25 random numbers sampled from a standard normal distribution.<br>
**Solution 1 :**

In [2]:
import numpy as np
rand = np.random.rand(25)
print(rand)

[0.04996977 0.22317238 0.21458393 0.26556107 0.48532946 0.16187742
 0.41970995 0.47867733 0.99976145 0.88148571 0.53163915 0.4963354
 0.37500875 0.57102084 0.87855771 0.14320297 0.0832768  0.87598993
 0.57288351 0.23373851 0.58367232 0.72265378 0.79785594 0.37251271
 0.3986205 ]


**Question 2 :** Create a random vector of size 30 and find the mean value.<br>
**Solution 2 :**

In [3]:
ran = np.random.randint(low=0,high=100,size=(30))
print("Mean : ",np.mean(ran))

Mean :  48.333333333333336


**Question 3 :** Insert 1 to 100 numbers in a numpy array and reshape it to 10x10 matrix.<br>
**Solution 3 :**

In [3]:
list1 = [i for i in range(1,101,1)]
arr = np.array([list1])
re_shape = np.reshape(arr,(10,10))
print(f"Matrix : {re_shape}",f"\nSize: {re_shape.size}")

Matrix : [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]] 
Size: 100


**Question 4 :** Create a 10x10 array with random values and find the minimum and maximum values.<br>
**Solution 4 :**

In [4]:
ran_val = np.random.randint(0,101,(10,10))
print(ran_val)
print(f"Min : {np.min(ran_val)}\nMax : {np.max(ran_val)}")

[[ 55  34  60   6  26  52  52  23  96  36]
 [ 48  92  69  75  94  54  94  13  16  76]
 [ 47  14 100  96   4  38  64  43  61  65]
 [ 28  72  96  80  51  48  53  25  60  43]
 [ 89  73  89  82  20  75  66  88   7  65]
 [ 11  76  32  39  40  35  33  44  17  76]
 [ 43  79   7  63  87  91  39  98  54  94]
 [ 41  44   8  41  86  60  15  50  22  61]
 [ 39  31  27  19  37  55  49  12  79  84]
 [ 24  49  47   0  53   4  19  85  21  20]]
Min : 0
Max : 100


**Question 5 :** Find Dot product of two arrays
                 f = np.array([1,2])
                 g = np.array([4,5])<br>
**Solution 5 :**                 
                 

In [5]:
f = np.array([1,2])
g = np.array([4,5])
print("Dot Product : ", np.dot(f,g))

Dot Product :  14


**Question 6 :** Concatenate following arrays along axis=0<br>
                 Ans: x=np.array([[1,2],[3,4]])<br>
                 y=np.array([[5,6]])<br>
**Solution 6 :**                 

In [6]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])
print("Concatenate following arrays along axis=0 : \n",np.concatenate((x,y),axis = 0))

Concatenate following arrays along axis=0 : 
 [[1 2]
 [3 4]
 [5 6]]


**Question 7 :** How to get the common items between two python numpy arrays?<br>
                 a = np.array([1,2,3,2,3,4,3,4,5,6])<br>
                 b = np.array([7,2,10,2,7,4,9,4,9,8])<br>
**Solution 7 :**                 

In [7]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("Common Items : " , np.intersect1d(a,b))

Common Items :  [2 4]


**Question 8 :** Sort the numpy array:<br>
                 arr = np.array([10,5,8,4,7,2,3,1])<br>
**Solution 8 :**

In [8]:
arr = np.array([10,5,8,4,7,2,3,1])
arr.sort()
print("sorted array : ",  arr)

sorted array :  [ 1  2  3  4  5  7  8 10]
